# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='boards',
            field=models.ManyToManyField(related_name='boards', to='Boards.Boards'),
        ),
    ]
