# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_date', models.DateField(default=datetime.datetime(2016, 11, 6, 14, 57, 18, 747344))),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardsAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null=True, upload_to='')),
                ('attachment', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('Check_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('data', models.CharField(max_length=1000)),
                ('checklist', models.ManyToManyField(related_name='checklist', to='Cards.ChecklistItems')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('card_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='database',
            field=models.ManyToManyField(related_name='databs', to='Cards.Data'),
        ),
    ]
