# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 6, 14, 58, 5, 110291)),
        ),
    ]
