# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0003_auto_20161107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 7, 13, 24, 47, 28825)),
        ),
    ]
