# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 05:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0004_auto_20161107_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_id',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cards',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 8, 10, 33, 17, 58000)),
        ),
    ]
