# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0005_auto_20161108_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('c_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cards.Card_id')),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 1, 0, 40, 130951)),
        ),
    ]
