# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_auto_20161112_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_id',
            name='change',
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 22, 11, 28, 58, 924000)),
        ),
        migrations.RemoveField(
            model_name='status',
            name='card_id',
        ),
        migrations.AddField(
            model_name='status',
            name='card_id',
            field=models.ManyToManyField(related_name='stats', to='Cards.Card_id'),
        ),
    ]
