# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0007_auto_20161122_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user_name',
            field=models.CharField(default=b' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 24, 0, 40, 12, 130000)),
        ),
    ]
